CREATE DATABASE dictionary_db;
USE dictionary_db;
CREATE TABLE words (
    id INT AUTO_INCREMENT PRIMARY KEY,
    word VARCHAR(255) NOT NULL,
    definition TEXT NOT NULL
);

INSERT INTO words (word, definition) VALUES
('algorithm', 'A step-by-step procedure for solving a problem or task.'),
('byte', 'A unit of digital information that consists of 8 bits.'),
('cache', 'A hardware or software component that stores data so future requests for that data can be served faster.'),
('database', 'An organized collection of structured information or data, typically stored electronically.'),
('encryption', 'The process of converting data into a code to prevent unauthorized access.'),
('firmware', 'Permanent software programmed into a read-only memory.'),
('gateway', 'A network point that acts as an access point to another network.'),
('hash function', 'A function that converts an input (or ''message'') into a fixed-size string of bytes.'),
('HTTP', 'Hypertext Transfer Protocol, an application protocol for distributed, collaborative, hypermedia information systems.'),
('IP address', 'A unique identifier for a device on a TCP/IP network.'),
('Java', 'A high-level programming language used to create applications across platforms.'),
('kilobyte', 'A unit of data equal to 1024 bytes.'),
('LED', 'Light Emitting Diode, a semiconductor device that emits light when current flows through it.'),
('microprocessor', 'An integrated circuit that contains the functions of a central processing unit (CPU) of a computer.'),
('network', 'A group of interconnected computers that share resources and information.'),
('operating system', 'Software that manages computer hardware and software resources and provides common services for computer programs.'),
('protocol', 'A set of rules governing the exchange or transmission of data between devices.'),
('query', 'A request for information from a database.'),
('router', 'A device that forwards data packets between computer networks.'),
('server', 'A computer or program that provides services to other computers or programs, known as clients.'),
('SQL', 'Structured Query Language, a standard programming language for managing and manipulating databases.'),
('TCP', 'Transmission Control Protocol, a core protocol of the Internet Protocol Suite that ensures reliable transmission of data.'),
('URL', 'Uniform Resource Locator, a reference or address used to access resources on the internet.'),
('virtual machine', 'An emulation of a computer system that provides the functionality of a physical computer.'),
('bandwidth', 'The maximum rate of data transfer across a network.'),
('debugging', 'The process of finding and resolving bugs or defects in software.'),
('firmware', 'Permanent software programmed into a read-only memory.'),
('GUI', 'Graphical User Interface, a visual way of interacting with a computer using items such as windows, icons, and buttons.'),
('inheritance', 'A feature of object-oriented programming where a class can inherit properties and methods from another class.'),
('join', 'An SQL operation that combines rows from two or more tables based on a related column.'),
('key', 'A field in a database that is used to uniquely identify a record.'),
('machine learning', 'A subset of artificial intelligence that involves the use of algorithms and statistical models for data analysis.'),
('namespace', 'A container that provides context for the names defined in a scope, ensuring that identifiers do not conflict.'),
('optimization', 'The process of making something as effective or functional as possible.'),
('queue', 'A collection of items waiting to be processed, often implemented as a FIFO (First In First Out) structure.'),
('runtime', 'The period during which a program is executing.'),
('schema', 'The structure that defines the organization of data in a database.'),
('token', 'A unit of information that can be processed by a program, often used in authentication.'),
('user interface', 'The means by which a user interacts with a computer or software application.'),
('version control', 'A system that records changes to files or sets of files over time so that specific versions can be recalled later.'),
('web server', 'A server that stores, processes, and delivers web pages to clients over the internet.'),
('XML', 'Extensible Markup Language, a markup language that defines rules for encoding documents in a format that is both human-readable and machine-readable.'),
('sandbox', 'A testing environment that isolates untested code changes and experiments from the production environment.'),
('load balancing', 'The process of distributing workloads across multiple computing resources to optimize resource use and avoid overload.'),
('repository', 'A central location in which data is stored and managed, often used for version control.'),
('scripting language', 'A programming language that is used for writing scripts that automate tasks.'),
('cloud computing', 'The delivery of computing services over the internet, allowing for on-demand access to resources.'),
('blockchain', 'A decentralized ledger technology that allows for secure and transparent transactions.'),
('API', 'Application Programming Interface, a set of rules and tools for building software applications.'),
('Docker', 'A platform for developing, shipping, and running applications in containers.'),
('Git', 'A version control system that tracks changes in source code during software development.'),
('load testing', 'A type of software testing that assesses the behavior of a system under specific expected loads.'),
('refactoring', 'The process of restructuring existing computer code without changing its external behavior.'),
('asynchronous', 'A form of communication in which data can be sent and received at different times.'),
('bandwidth', 'The maximum rate at which data can be transmitted over a network path.'),
('bootstrap', 'A process of loading a simple program to initialize the operating system.'),
('cloud storage', 'A model of computer data storage in which the digital data is stored in logical pools, the physical storage spans multiple servers.'),
('compiler', 'A program that converts source code written in a high-level programming language into machine code.'),
('containerization', 'A form of virtualization that allows you to run multiple isolated applications on a single host using shared operating system resources.'),
('data mining', 'The practice of analyzing large datasets to uncover patterns and extract useful information.'),
('encryption key', 'A string of bits used by an algorithm to convert data into a secure format.'),
('frontend', 'The part of a software application that interacts directly with users, including UI/UX design.'),
('git workflow', 'A set of conventions for how to manage code changes and version control processes when using Git.'),
('hash table', 'A data structure that implements an associative array abstract data type, a structure that can map keys to values.'),
('inheritance', 'A mechanism to create a new class using the properties and methods of another class in Object-Oriented Programming.'),
('JIT compilation', 'Just-In-Time compilation, an approach in which code is compiled into machine code just before it is executed.'),
('kernels', 'The central component of an operating system that manages system resources and hardware communication.'),
('load balancer', 'A device that distributes network or application traffic across multiple servers.'),
('middleware', 'Software that acts as a bridge between different software applications or services.'),
('network topography', 'The arrangement of different elements (links, nodes, etc.) in a computer network.'),
('object-oriented programming', 'A programming paradigm based on the concept of "objects", which can contain data and code.'),
('packet switching', 'A method of data transmission in which messages are divided into packets and sent independently over the network.'),
('query optimization', 'Techniques used to improve the performance of a database query.'),
('RESTful API', 'An API that conforms to the REST architectural style, allowing for interaction over HTTP.'),
('scalability', 'The capability of a system to handle a growing amount of work or its potential to be enlarged to accommodate that growth.'),
('stack overflow', 'An error that occurs when a program uses more memory space on the call stack than is allocated.'),
('TCP/IP', 'Transmission Control Protocol/Internet Protocol, a fundamental suite of protocols for network communication.'),
('unicode', 'An industry standard for encoding, representing, and managing text, allowing characters from all languages.'),
('versioning', 'The process of assigning unique version identifiers to different states of a document or data.'),
('w3c', 'World Wide Web Consortium, an international community that develops open standards to ensure long-term growth of the Web.'),
('XSS', 'Cross-Site Scripting, a security vulnerability that allows attackers to inject malicious scripts into web pages viewed by other users.'),
('YAML', 'YAML Ain’t Markup Language, a human-readable data serialization standard often used for configuration files.'),
('zipping', 'The process of compressing one or more files to reduce their total size, often using .zip file format.'),
('agile methodology', 'An approach to project management and software development that emphasizes flexibility, collaboration, and customer satisfaction.'),
('browser caching', 'A mechanism that stores webpage resources temporarily to improve loading times for repeated visits.'),
('cloud-native', 'An approach to building and running applications that fully exploit the advantages of the cloud computing delivery model.'),
('dependency injection', 'A design pattern used to implement IoC (Inversion of Control), allowing for more flexible code management.'),
('event-driven programming', 'A programming paradigm in which the flow of the program is determined by events such as user actions or sensor outputs.'),
('fault tolerance', 'The property of a system to continue functioning correctly even in the event of a failure of some of its components.'),
('garbage collection', 'The process of automatically reclaiming memory by removing data that is no longer in use by the program.'),
('hypervisor', 'A software layer that enables virtualization by allowing multiple operating systems to run concurrently on a host machine.'),
('internet of things', 'The interconnection of everyday devices to the internet, allowing them to send and receive data.'),
('JavaScript', 'A high-level programming language commonly used in web development to create interactive effects within web browsers.'),
('Kubernetes', 'An open-source platform designed to automate deploying, scaling, and operating application containers.'),
('machine vision', 'An interdisciplinary subfield of computer science that enables computers to interpret and process visual information from the world.'),
('neural network', 'A computational model inspired by the way biological neural networks in the human brain process information.'),
('API endpoint', 'A specific URL where an API can be accessed to perform operations or retrieve data.'),
('BIOS', 'Basic Input/Output System, firmware used during the startup process of a computer.'),
('circuit', 'A path for electrical current that can be open or closed, allowing for the flow of electricity.'),
('data warehouse', 'A system used for reporting and data analysis that serves as a central repository of integrated data from multiple sources.'),
('edge computing', 'A distributed computing paradigm which promotes bringing computation and data storage closer to the location where it is needed.'),
('full stack', 'A term that refers to both front-end and back-end development of web applications.'),
('ghost writing', "Writing for another person's name, often used in the context of content creation without public credit."),
('iterative development', 'A method of software development where the project is built and improved through repeated cycles.'),
('Java Virtual Machine', 'An abstract computing machine that enables a computer to run Java programs.'),
('KPI', 'Key Performance Indicator, a measurable value that demonstrates how effectively a company is achieving key business objectives.'),
('load testing', 'The process of putting demand on a system and measuring its response to that demand.'),
('microservices', 'An architectural style that structures an application as a collection of small, loosely coupled services.'),
('null pointer exception', 'An error that occurs when a program attempts to use an object reference that has not been initialized.'),
('OAuth', 'Open Authorization, a protocol that allows secure authorization from third-party applications without sharing passwords.'),
('pixel', 'The smallest unit of a digital image or display that can be represented on screen.');